#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIRewardItemResource
@end

@interface JSAPIRewardItemResource : JSAPIObject

/* The id of the item to reward 
 */
@property(nonatomic) NSNumber* itemId;
/* The name of the item to reward (read only, set by id) [optional]
 */
@property(nonatomic) NSString* itemName;
/* The highest number (worst) rank to give the reward to. Must be greater than or equal to minRank 
 */
@property(nonatomic) NSNumber* maxRank;
/* The lowest number (best) rank to give the reward to. Must be greater than zero 
 */
@property(nonatomic) NSNumber* minRank;
/* How many copies to give 
 */
@property(nonatomic) NSNumber* quantity;

+ (NSDictionary *)modalDictionary;

@end
