#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIMetricResource
@end

@interface JSAPIMetricResource : JSAPIObject

/* The id of the activity occurence where this score/metric occurred 
 */
@property(nonatomic) NSNumber* activityOccurenceId;
/* Any tags for the metric. Each unique tag will translate into a unique leaderboard. Maximum 10 tags and 50 characters each [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;
/* The id of the user this metric is for. Default to caller and requires METRICS_ADMIN permission to specify another [optional]
 */
@property(nonatomic) NSNumber* userId;
/* The value/score of the metric 
 */
@property(nonatomic) NSNumber* value;

+ (NSDictionary *)modalDictionary;

@end
