#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIMessageContentResource.h"
@protocol JSAPIMessageContentResource;
@class JSAPIMessageContentResource;



@protocol JSAPIMessageResource
@end

@interface JSAPIMessageResource : JSAPIObject

/* The content of the message in various formats 
 */
@property(nonatomic) JSAPIMessageContentResource* content;
/* The id of the recipient, dependent on the recipient_type. The user's id or the topic's id. Required if sending directly to messaging service [optional]
 */
@property(nonatomic) NSString* recipient;
/* The type of recipient for the message. Either a user, or all users in a topic. Required if sending directly to messaging service [optional]
 */
@property(nonatomic) NSString* recipientType;
/* The subject of the message. Required for email messages [optional]
 */
@property(nonatomic) NSString* subject;
/* The type of message for websocket type hinting. will be added to the payload with the key _type [optional]
 */
@property(nonatomic) NSString* type;

+ (NSDictionary *)modalDictionary;

@end
