#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPITopicResource
@end

@interface JSAPITopicResource : JSAPIObject

/* The created date of the topic [optional]
 */
@property(nonatomic) NSNumber* createdDate;
/* The display name of the topic [optional]
 */
@property(nonatomic) NSString* displayName;
/* The unique ID for this topic [optional]
 */
@property(nonatomic) NSString* _id;
/* Whether this topic is locked or not. [optional]
 */
@property(nonatomic) NSNumber* locked;
/* Random tags to facilitate search [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;
/* The last time the topic was updated [optional]
 */
@property(nonatomic) NSNumber* updatedDate;
/* The subscribed user count of the topic [optional]
 */
@property(nonatomic) NSNumber* userCount;

+ (NSDictionary *)modalDictionary;

@end
