#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIAnswerResource.h"
#import "JSAPINestedCategory.h"
#import "JSAPIProperty.h"
@protocol JSAPIAnswerResource;
@class JSAPIAnswerResource;
@protocol JSAPINestedCategory;
@class JSAPINestedCategory;
@protocol JSAPIProperty;
@class JSAPIProperty;



@protocol JSAPIQuestionResource
@end

@interface JSAPIQuestionResource : JSAPIObject

/* A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type [optional]
 */
@property(nonatomic) NSDictionary* additionalProperties;
/* The list of available answers [optional]
 */
@property(nonatomic) NSArray<JSAPIAnswerResource>* answers;
/* The category for the question 
 */
@property(nonatomic) JSAPINestedCategory* category;
/* The date/time this resource was created in seconds since unix epoch [optional]
 */
@property(nonatomic) NSNumber* createdDate;
/* The difficulty of the question 
 */
@property(nonatomic) NSNumber* difficulty;
/* The unique ID for that resource [optional]
 */
@property(nonatomic) NSString* _id;
/* The id of the import job that created the question, or null if not from an import [optional]
 */
@property(nonatomic) NSNumber* importId;
/* When the question becomes available, null for never, in seconds since epoch [optional]
 */
@property(nonatomic) NSNumber* publishedDate;
/* The question. Different 'type' values indicate different structures as the question may be test, image, etc. See information on additional properties for the list and their structures 
 */
@property(nonatomic) JSAPIProperty* question;
/* The first source of the question [optional]
 */
@property(nonatomic) NSString* source1;
/* The second source of the question [optional]
 */
@property(nonatomic) NSString* source2;
/* The list of tags [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;
/* A question template this question is validated against (private). May be null and no validation of additional_properties will be done [optional]
 */
@property(nonatomic) NSString* template;
/* The date/time this resource was last updated in seconds since unix epoch [optional]
 */
@property(nonatomic) NSNumber* updatedDate;
/* The supplier of the question [optional]
 */
@property(nonatomic) NSString* vendor;

+ (NSDictionary *)modalDictionary;

@end
