#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIPropertyDefinitionResource.h"
#import "JSAPIPropertyFieldListResource.h"
@protocol JSAPIPropertyDefinitionResource;
@class JSAPIPropertyDefinitionResource;
@protocol JSAPIPropertyFieldListResource;
@class JSAPIPropertyFieldListResource;



@protocol JSAPIMapPropertyDefinitionResource
@end

@interface JSAPIMapPropertyDefinitionResource : JSAPIPropertyDefinitionResource

/* Whether to allow additional properties beyond those specified or not [optional]
 */
@property(nonatomic) NSNumber* allowAdditional;
/* If provided, a list of property definitions for each map entry [optional]
 */
@property(nonatomic) NSArray<JSAPIPropertyDefinitionResource>* properties;


@end
