#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIPropertyDefinitionResource.h"
#import "JSAPIPropertyFieldListResource.h"
@protocol JSAPIPropertyDefinitionResource;
@class JSAPIPropertyDefinitionResource;
@protocol JSAPIPropertyFieldListResource;
@class JSAPIPropertyFieldListResource;



@protocol JSAPIVideoPropertyDefinitionResource
@end

@interface JSAPIVideoPropertyDefinitionResource : JSAPIPropertyDefinitionResource

/* If provided, a file type that teh property must match [optional]
 */
@property(nonatomic) NSString* fileType;
/* If provided, the maximum height of the video [optional]
 */
@property(nonatomic) NSNumber* maxHeight;
/* If provided, the maximum length of the video [optional]
 */
@property(nonatomic) NSNumber* maxLength;
/* If provided, the maximum width of the video [optional]
 */
@property(nonatomic) NSNumber* maxWidth;
/* If provided, the minimum height of the video [optional]
 */
@property(nonatomic) NSNumber* minHeight;
/* If provided, the minimum length of the video [optional]
 */
@property(nonatomic) NSNumber* minLength;
/* If provided, the minimum width of the video [optional]
 */
@property(nonatomic) NSNumber* minWidth;


@end
