#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIMessageTemplateResource
@end

@interface JSAPIMessageTemplateResource : JSAPIObject

/* The content of the template. See Apache Velocity documentation for formatting 
 */
@property(nonatomic) NSString* content;
/* The id of the template. Cannot be changed after creation. default: auto generated [optional]
 */
@property(nonatomic) NSString* _id;
/* The name of the template 
 */
@property(nonatomic) NSString* name;
/* A list of tags for search purposes. Will be converted to lower case [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;

+ (NSDictionary *)modalDictionary;

@end
