#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIBareChallengeActivityResource
@end

@interface JSAPIBareChallengeActivityResource : JSAPIObject

/* The id of the activity 
 */
@property(nonatomic) NSNumber* activityId;
/* The id of the challenge 
 */
@property(nonatomic) NSNumber* challengeId;
/* The unique ID for this resource [optional]
 */
@property(nonatomic) NSNumber* _id;

+ (NSDictionary *)modalDictionary;

@end
