#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIS3Config
@end

@interface JSAPIS3Config : JSAPIObject


@property(nonatomic) NSString* bucketName;

@property(nonatomic) NSString* cdnUrl;

@property(nonatomic) NSString* region;

@property(nonatomic) NSString* uploadPrefix;

+ (NSDictionary *)modalDictionary;

@end
