#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIArgumentResource.h"
#import "JSAPIOperator.h"
@protocol JSAPIArgumentResource;
@class JSAPIArgumentResource;
@protocol JSAPIOperator;
@class JSAPIOperator;



@protocol JSAPIOperationDefinitionResource
@end

@interface JSAPIOperationDefinitionResource : JSAPIObject


@property(nonatomic) NSArray<JSAPIArgumentResource>* arguments;

@property(nonatomic) NSString* _description;

@property(nonatomic) JSAPIOperator* operator;

@property(nonatomic) NSString* returnType;

@property(nonatomic) NSString* template;

+ (NSDictionary *)modalDictionary;

@end
