#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIProperty.h"
#import "JSAPISubscriptionPlanResource.h"


@protocol JSAPISubscriptionResource
@end

@interface JSAPISubscriptionResource : JSAPIObject

/* A map of item additional properties, keyed on the property name. Must match the names and types defined in the template for this item type. [optional]
 */
@property(nonatomic) NSDictionary<JSAPIProperty>* additionalProperties;
/* Who can purchase this subscription [optional]
 */
@property(nonatomic) NSString* availability;
/* A category for filtering items [optional]
 */
@property(nonatomic) NSString* category;
/* The day of the month 1..31 this subscription will renew [optional]
 */
@property(nonatomic) NSNumber* consolidationDayOfMonth;
/* The date the item was created, unix timestamp in seconds [optional]
 */
@property(nonatomic) NSNumber* createdDate;
/* A list of country iso3 codes to include in the blacklist/whitelist geo policy [optional]
 */
@property(nonatomic) NSArray<NSString*>* geoCountryList;
/* Whether to use the geo_country_list as a black list or white list for item geographical availability [optional]
 */
@property(nonatomic) NSString* geoPolicyType;
/* The id of the item [optional]
 */
@property(nonatomic) NSNumber* _id;
/* A long description of the subscription [optional]
 */
@property(nonatomic) NSString* longDescription;
/* The name of the item 
 */
@property(nonatomic) NSString* name;
/* The billing options for this subscription [optional]
 */
@property(nonatomic) NSArray<JSAPISubscriptionPlanResource>* plans;
/* A short description of the subscription.  Max 255 characters [optional]
 */
@property(nonatomic) NSString* shortDescription;
/* A number to use in sorting items.  Default 500 [optional]
 */
@property(nonatomic) NSNumber* sort;
/* Used to schedule removal from store.  Null means the subscription will never be removed [optional]
 */
@property(nonatomic) NSNumber* storeEnd;
/* Used to schedule appearance in store.  Null means the subscription will appear now [optional]
 */
@property(nonatomic) NSNumber* storeStart;
/* List of tags used for filtering items [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;
/* An item template this item is validated against. May be null and no validation of additional properties will be done. [optional]
 */
@property(nonatomic) NSString* template;
/* The unique key for the item [optional]
 */
@property(nonatomic) NSString* uniqueKey;
/* The date the item was last updated [optional]
 */
@property(nonatomic) NSNumber* updatedDate;
/* The vendor who provides the item 
 */
@property(nonatomic) NSNumber* vendorId;

+ (NSDictionary *)modalDictionary;

@end
