#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIPaymentMethodResource.h"
#import "JSAPISimpleUserResource.h"
#import "JSAPISubscriptionCreditResource.h"
@protocol JSAPIPaymentMethodResource;
@class JSAPIPaymentMethodResource;
@protocol JSAPISimpleUserResource;
@class JSAPISimpleUserResource;
@protocol JSAPISubscriptionCreditResource;
@class JSAPISubscriptionCreditResource;



@protocol JSAPIInventorySubscriptionResource
@end

@interface JSAPIInventorySubscriptionResource : JSAPIObject

/* The date the subscription will be billed [optional]
 */
@property(nonatomic) NSNumber* billDate;
/* A credit of money already applied to a subscription for the next bill, or a debt if negative [optional]
 */
@property(nonatomic) NSNumber* credit;
/* A record of past and present credit/debt changes [optional]
 */
@property(nonatomic) NSArray<JSAPISubscriptionCreditResource>* creditLog;
/* The date the grace period ends [optional]
 */
@property(nonatomic) NSNumber* graceEnd;
/* The id of the inventory [optional]
 */
@property(nonatomic) NSNumber* inventoryId;
/* The inventory status object [optional]
 */
@property(nonatomic) NSString* inventoryStatus;
/* The id of the item [optional]
 */
@property(nonatomic) NSNumber* itemId;
/* The payment method object [optional]
 */
@property(nonatomic) JSAPIPaymentMethodResource* paymentMethod;
/* The recurring price that has been set to override the base price. Null if not overriding [optional]
 */
@property(nonatomic) NSNumber* priceOverride;
/* An explanation for the reason the price is being overridden [optional]
 */
@property(nonatomic) NSString* priceOverrideReason;
/* The default recurring price [optional]
 */
@property(nonatomic) NSNumber* recurringPrice;
/* The recurring sku of the subscription [optional]
 */
@property(nonatomic) NSString* sku;
/* The date the subscription will start [optional]
 */
@property(nonatomic) NSNumber* startDate;
/* The status of the subscription [optional]
 */
@property(nonatomic) NSNumber* subscriptionStatus;
/* The user [optional]
 */
@property(nonatomic) JSAPISimpleUserResource* user;

+ (NSDictionary *)modalDictionary;

@end
