#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIErrorResource
@end

@interface JSAPIErrorResource : JSAPIObject

/* Extra details about the error, if needed [optional]
 */
@property(nonatomic) NSObject* details;
/* The JSON key the message pertains to [optional]
 */
@property(nonatomic) NSObject* field;
/* The message explaining the error [optional]
 */
@property(nonatomic) NSString* message;

+ (NSDictionary *)modalDictionary;

@end
