#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIProperty.h"
@protocol JSAPIProperty;
@class JSAPIProperty;



@protocol JSAPIGroupResource
@end

@interface JSAPIGroupResource : JSAPIObject

/* A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type [optional]
 */
@property(nonatomic) NSDictionary* additionalProperties;
/* A description of the group [optional]
 */
@property(nonatomic) NSString* _description;
/* The number of users in the group [optional]
 */
@property(nonatomic) NSNumber* memberCount;
/* A message of the day for members of the group [optional]
 */
@property(nonatomic) NSString* messageOfTheDay;
/* The name of the group. Max 50 characters 
 */
@property(nonatomic) NSString* name;
/* The unique name of another group that this group is a subset of [optional]
 */
@property(nonatomic) NSString* parent;
/* The status which describes whether other users can freely join the group or not 
 */
@property(nonatomic) NSString* status;
/* The number of users in child groups [optional]
 */
@property(nonatomic) NSNumber* subMemberCount;
/* Tags for search [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;
/* A group template this group is validated against. May be null and no validation of additional_properties will be done [optional]
 */
@property(nonatomic) NSString* template;
/* Unique name used in url and references. Uppercase, lowercase, numbers and hyphens only. Max 50 characters. Cannot be altered once created. Default: random UUID [optional]
 */
@property(nonatomic) NSString* uniqueName;

+ (NSDictionary *)modalDictionary;

@end
