#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIActionContextObject_.h"
#import "JSAPIPredicateResource.h"
@protocol JSAPIActionContextObject_;
@class JSAPIActionContextObject_;
@protocol JSAPIPredicateResource;
@class JSAPIPredicateResource;



@protocol JSAPIBreRule
@end

@interface JSAPIBreRule : JSAPIObject

/* A list of actions to execute, and the mapping for their parameters, when the rule runs. Minimum 1 
 */
@property(nonatomic) NSArray<JSAPIActionContextObject_>* actions;
/* A condition expression that must be met in a given event for the rule to run. Null to always run. [optional]
 */
@property(nonatomic) JSAPIPredicateResource* condition;
/* The condition as a readable string. Filled in by the system from the condition [optional]
 */
@property(nonatomic) NSString* conditionText;
/* The human readable description of the rule [optional]
 */
@property(nonatomic) NSString* _description;
/* Whether the rule is enabled to run (in conjunction with dates). Default true [optional]
 */
@property(nonatomic) NSNumber* enabled;
/* The date the rule ceases to take effect, or null if never. Unix timestamp in seconds [optional]
 */
@property(nonatomic) NSNumber* endDate;
/* How many times the rule has been evaluated (it's conditions checked, whether it then runs or not) [optional]
 */
@property(nonatomic) NSNumber* evaluationCount;
/* The event name of the trigger this rule runs for. Affects which parameters are available 
 */
@property(nonatomic) NSString* eventName;
/* The id of the rule for later references. If left null a random guid will be generated. Must be unique. Cannot be changed [optional]
 */
@property(nonatomic) NSString* _id;
/* The human readable name of the rule 
 */
@property(nonatomic) NSString* name;
/* How many times the rule has run [optional]
 */
@property(nonatomic) NSNumber* runCount;
/* Used to sort rules to control the order they run in. Larger numbered sort values run first.  Default 500 [optional]
 */
@property(nonatomic) NSNumber* sort;
/* The date the rule begins to take effect, or null if always. Unix timestamp in seconds [optional]
 */
@property(nonatomic) NSNumber* startDate;
/* Whether the rule is a default part of the system. System rules cannot be edited or deleted, but may be disabled [optional]
 */
@property(nonatomic) NSNumber* systemRule;

+ (NSDictionary *)modalDictionary;

@end
