#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIBehavior.h"
#import "JSAPIProperty.h"
#import "JSAPISubscriptionPlanResource.h"
@protocol JSAPIBehavior;
@class JSAPIBehavior;
@protocol JSAPIProperty;
@class JSAPIProperty;
@protocol JSAPISubscriptionPlanResource;
@class JSAPISubscriptionPlanResource;



@protocol JSAPISubscriptionResource
@end

@interface JSAPISubscriptionResource : JSAPIObject

/* The additional properties for the subscription [optional]
 */
@property(nonatomic) NSDictionary* additionalProperties;
/* Who can purchase this subscription [optional]
 */
@property(nonatomic) NSString* availability;
/* The behaviors linked to the item, describing various options and interactions. May not be included in item lists [optional]
 */
@property(nonatomic) NSArray<JSAPIBehavior>* behaviors;
/* The category of the subscription [optional]
 */
@property(nonatomic) NSString* category;
/* The day of the month 1..31 this subscription will renew [optional]
 */
@property(nonatomic) NSNumber* consolidationDayOfMonth;
/* The date the item was created, unix timestamp in seconds [optional]
 */
@property(nonatomic) NSNumber* createdDate;
/* Whether or not the item is currently visible to users. Does not block purchase; Use store_start or store_end to block purchase.  Default = true [optional]
 */
@property(nonatomic) NSNumber* displayable;
/* The geo country list for the subscription [optional]
 */
@property(nonatomic) NSArray<NSString*>* geoCountryList;
/* The geo policy type for the subscription [optional]
 */
@property(nonatomic) NSString* geoPolicyType;
/* The id of the item [optional]
 */
@property(nonatomic) NSNumber* _id;
/* A long description of the subscription [optional]
 */
@property(nonatomic) NSString* longDescription;
/* The name of the item 
 */
@property(nonatomic) NSString* name;
/* The billing options for this subscription [optional]
 */
@property(nonatomic) NSArray<JSAPISubscriptionPlanResource>* plans;
/* A short description of the subscription.  Max 255 characters [optional]
 */
@property(nonatomic) NSString* shortDescription;
/* A number to use in sorting items.  Default 500 [optional]
 */
@property(nonatomic) NSNumber* sort;
/* Used to schedule removal from store.  Null means the subscription will never be removed [optional]
 */
@property(nonatomic) NSNumber* storeEnd;
/* Used to schedule appearance in store.  Null means the subscription will appear now [optional]
 */
@property(nonatomic) NSNumber* storeStart;
/* The tags for the subscription [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;
/* The template being used [optional]
 */
@property(nonatomic) NSString* template;
/* The unique key of the subscription [optional]
 */
@property(nonatomic) NSString* uniqueKey;
/* The date the item was last updated [optional]
 */
@property(nonatomic) NSNumber* updatedDate;
/* The id of the vendor 
 */
@property(nonatomic) NSNumber* vendorId;

+ (NSDictionary *)modalDictionary;

@end
