#import <Foundation/Foundation.h>
#import "JSAPICountryResource.h"
#import "JSAPICurrencyResource.h"
#import "JSAPIResult.h"
#import "JSAPIStateResource.h"
#import "JSAPIApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface JSAPILocationsApi: NSObject <JSAPIApi>

extern NSString* kJSAPILocationsApiErrorDomain;
extern NSInteger kJSAPILocationsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(JSAPIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get a list of countries
/// <b>Permissions Needed:</b> ANY
///
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSArray<JSAPICountryResource>*
-(NSURLSessionTask*) getCountriesWithCompletionHandler: 
    (void (^)(NSArray<JSAPICountryResource>* output, NSError* error)) handler;


/// Get the iso3 code of your country
/// Determined by geo ip location. <br><br><b>Permissions Needed:</b> ANY
///
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSString*
-(NSURLSessionTask*) getCountryByGeoLocationWithCompletionHandler: 
    (void (^)(NSString* output, NSError* error)) handler;


/// Get a list of a country's states
/// <b>Permissions Needed:</b> ANY
///
/// @param countryCodeIso3 The iso3 code of the country
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSArray<JSAPIStateResource>*
-(NSURLSessionTask*) getCountryStatesWithCountryCodeIso3: (NSString*) countryCodeIso3
    completionHandler: (void (^)(NSArray<JSAPIStateResource>* output, NSError* error)) handler;


/// Get the currency information of your country
/// Determined by geo ip location, currency to country mapping and a fallback setting. <br><br><b>Permissions Needed:</b> ANY
///
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return JSAPICurrencyResource*
-(NSURLSessionTask*) getCurrencyByGeoLocationWithCompletionHandler: 
    (void (^)(JSAPICurrencyResource* output, NSError* error)) handler;



@end
