#import <Foundation/Foundation.h>
#import "JSAPIPageResourceBillingReport_.h"
#import "JSAPIResult.h"
#import "JSAPIApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface JSAPIReportingSubscriptionsApi: NSObject <JSAPIApi>

extern NSString* kJSAPIReportingSubscriptionsApiErrorDomain;
extern NSInteger kJSAPIReportingSubscriptionsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(JSAPIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get a list of available subscription reports in most recent first order
/// <b>Permissions Needed:</b> SUBSCRIPTIONS_ADMIN
///
/// @param size The number of objects returned per page (optional) (default to 25)
/// @param page The number of the page returned, starting with 1 (optional) (default to 1)
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return JSAPIPageResourceBillingReport_*
-(NSURLSessionTask*) getSubscriptionReportsWithSize: (NSNumber*) size
    page: (NSNumber*) page
    completionHandler: (void (^)(JSAPIPageResourceBillingReport_* output, NSError* error)) handler;



@end
