#import <Foundation/Foundation.h>
#import "JSAPIBatch.h"
#import "JSAPIBatchReturn.h"
#import "JSAPIResult.h"
#import "JSAPIApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface JSAPIUtilBatchApi: NSObject <JSAPIApi>

extern NSString* kJSAPIUtilBatchApiErrorDomain;
extern NSInteger kJSAPIUtilBatchApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(JSAPIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Request to run API call given the method, content type, path url, and body of request
/// 
///
/// @param batch The batch object (optional)
/// 
///  code:207 message:"Multi-Status",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSArray<JSAPIBatchReturn>*
-(NSURLSessionTask*) sendBatchWithBatch: (JSAPIBatch*) batch
    completionHandler: (void (^)(NSArray<JSAPIBatchReturn>* output, NSError* error)) handler;



@end
