#import <Foundation/Foundation.h>
#import "JSAPIFulfillmentType.h"
#import "JSAPIPageResourceFulfillmentType_.h"
#import "JSAPIResult.h"
#import "JSAPIApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface JSAPIFulfillmentApi: NSObject <JSAPIApi>

extern NSString* kJSAPIFulfillmentApiErrorDomain;
extern NSInteger kJSAPIFulfillmentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(JSAPIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create a fulfillment type
/// <b>Permissions Needed:</b> FULFILLMENT_ADMIN
///
/// @param type The fulfillment type (optional)
/// 
///  code:201 message:"Created",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return JSAPIFulfillmentType*
-(NSURLSessionTask*) createFulfillmentTypeWithType: (JSAPIFulfillmentType*) type
    completionHandler: (void (^)(JSAPIFulfillmentType* output, NSError* error)) handler;


/// Delete a fulfillment type
/// <b>Permissions Needed:</b> FULFILLMENT_ADMIN
///
/// @param _id The id
/// 
///  code:204 message:"No Content",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return void
-(NSURLSessionTask*) deleteFulfillmentTypeWithId: (NSNumber*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Get a single fulfillment type
/// <b>Permissions Needed:</b> ANY
///
/// @param _id The id
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return JSAPIFulfillmentType*
-(NSURLSessionTask*) getFulfillmentTypeWithId: (NSNumber*) _id
    completionHandler: (void (^)(JSAPIFulfillmentType* output, NSError* error)) handler;


/// List and search fulfillment types
/// <b>Permissions Needed:</b> ANY
///
/// @param size The number of objects returned per page (optional) (default to 25)
/// @param page The number of the page returned, starting with 1 (optional) (default to 1)
/// @param order A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional) (default to id:ASC)
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return JSAPIPageResourceFulfillmentType_*
-(NSURLSessionTask*) getFulfillmentTypesWithSize: (NSNumber*) size
    page: (NSNumber*) page
    order: (NSString*) order
    completionHandler: (void (^)(JSAPIPageResourceFulfillmentType_* output, NSError* error)) handler;


/// Update a fulfillment type
/// <b>Permissions Needed:</b> FULFILLMENT_ADMIN
///
/// @param _id The fulfillment id
/// @param fulfillmentType The fulfillment type (optional)
/// 
///  code:204 message:"No Content",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return void
-(NSURLSessionTask*) updateFulfillmentTypeWithId: (NSNumber*) _id
    fulfillmentType: (JSAPIFulfillmentType*) fulfillmentType
    completionHandler: (void (^)(NSError* error)) handler;



@end
