#import <Foundation/Foundation.h>
#import "SWGAmazonS3Activity.h"
#import "SWGApi.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGAWSS3Api: NSObject <SWGApi>

extern NSString* kSWGAWSS3ApiErrorDomain;
extern NSInteger kSWGAWSS3ApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Get a signed S3 URL
/// Requires the file name and file content type (i.e., 'video/mpeg')
///
/// @param filename The file name (optional)
/// @param contentType The content type (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGAmazonS3Activity*
-(NSNumber*) preSignUrlUsingGETWithFilename: (NSString*) filename
    contentType: (NSString*) contentType
    completionHandler: (void (^)(SWGAmazonS3Activity* output, NSError* error)) handler;



@end
