#import <Foundation/Foundation.h>
#import "SWGActionResource.h"
#import "SWGApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGBRERuleEngineActionsApi: NSObject <SWGApi>

extern NSString* kSWGBRERuleEngineActionsApiErrorDomain;
extern NSInteger kSWGBRERuleEngineActionsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get a list of available actions
/// 
///
/// @param filterCategory Filter for actions that are within a specific category (optional)
/// @param filterName Filter for actions that have names containing the given string (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSArray<SWGActionResource>*
-(NSURLSessionTask*) getBREActionsWithFilterCategory: (NSString*) filterCategory
    filterName: (NSString*) filterName
    completionHandler: (void (^)(NSArray<SWGActionResource>* output, NSError* error)) handler;



@end
