#import <Foundation/Foundation.h>
#import "SWGBreEvent.h"
#import "SWGApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGBRERuleEngineEventsApi: NSObject <SWGApi>

extern NSString* kSWGBRERuleEngineEventsApiErrorDomain;
extern NSInteger kSWGBRERuleEngineEventsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Fire a new event, based on an existing trigger
/// Parameters within the event must match names and types from the trigger. Actual rule execution is asynchornous.
///
/// @param breEvent The BRE event object (optional)
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return 
-(NSURLSessionTask*) fireEventUsingPOSTWithBreEvent: (SWGBreEvent*) breEvent
    completionHandler: (void (^)(NSError* error)) handler;



@end
