#import <Foundation/Foundation.h>
#import "SWGCustomerConfig.h"
#import "SWGCustomerResource.h"
#import "SWGApi.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGCustomerserviceApi: NSObject <SWGApi>

extern NSString* kSWGCustomerserviceApiErrorDomain;
extern NSInteger kSWGCustomerserviceApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Create a customer
/// 
///
/// @param customer customer
/// 
///  code:201 message:"Created",
///  code:202 message:"Accepted",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return 
-(NSNumber*) createCustomerUsingPOSTWithCustomer: (SWGCustomerConfig*) customer
    completionHandler: (void (^)(NSError* error)) handler;


/// List and search customers
/// Get a list of customers with optional filtering
///
/// @param size The number of objects returned per page (optional) (default to 25)
/// @param page The number of the page returned, starting with 1 (optional) (default to 1)
/// @param order A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional) (default to 1)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSArray<SWGCustomerResource>*
-(NSNumber*) getCustomersUsingGETWithSize: (NSNumber*) size
    page: (NSNumber*) page
    order: (NSString*) order
    completionHandler: (void (^)(NSArray<SWGCustomerResource>* output, NSError* error)) handler;



@end
