#import <Foundation/Foundation.h>
#import "SWGGooglePaymentRequest.h"
#import "SWGApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGPaymentsGoogleApi: NSObject <SWGApi>

extern NSString* kSWGPaymentsGoogleApiErrorDomain;
extern NSInteger kSWGPaymentsGoogleApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Mark an invoice paid with Google
/// Mark an invoice paid with Google. Verifies signature from Google and treats the developerPayload field inside the json payload as the id of the invoice to pay. Returns the transaction ID if successful.
///
/// @param request The request for paying an invoice through a Google in-app payment (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSNumber*
-(NSURLSessionTask*) handlePaymentUsingPOSTWithRequest: (SWGGooglePaymentRequest*) request
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;



@end
