#import <Foundation/Foundation.h>
#import "SWGCatalogSale.h"
#import "SWGPageCatalogSale_.h"
#import "SWGApi.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGStoreSalesApi: NSObject <SWGApi>

extern NSString* kSWGStoreSalesApiErrorDomain;
extern NSInteger kSWGStoreSalesApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Create a sale
/// 
///
/// @param catalogSale The catalog sale object (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCatalogSale*
-(NSNumber*) createCatalogSaleUsingPOSTWithCatalogSale: (SWGCatalogSale*) catalogSale
    completionHandler: (void (^)(SWGCatalogSale* output, NSError* error)) handler;


/// Delete a sale
/// 
///
/// @param _id The id of the sale
/// 
///  code:204 message:"No Content",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden"
///
/// @return 
-(NSNumber*) deleteCatalogSaleUsingDELETEWithId: (NSNumber*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Get a single sale
/// 
///
/// @param _id The id of the sale
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGCatalogSale*
-(NSNumber*) getCatalogSaleUsingGETWithId: (NSNumber*) _id
    completionHandler: (void (^)(SWGCatalogSale* output, NSError* error)) handler;


/// List and search sales
/// 
///
/// @param size The number of objects returned per page (optional) (default to 25)
/// @param page The number of the page returned, starting with 1 (optional) (default to 1)
/// @param order a comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional) (default to 1)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGPageCatalogSale_*
-(NSNumber*) getCatalogSalesUsingGETWithSize: (NSNumber*) size
    page: (NSNumber*) page
    order: (NSString*) order
    completionHandler: (void (^)(SWGPageCatalogSale_* output, NSError* error)) handler;


/// Update a sale
/// 
///
/// @param _id The id of the sale
/// @param catalogSale The catalog sale object (optional)
/// 
///  code:201 message:"Created",
///  code:204 message:"No Content",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return 
-(NSNumber*) updateCatalogSaleUsingPUTWithId: (NSNumber*) _id
    catalogSale: (SWGCatalogSale*) catalogSale
    completionHandler: (void (^)(NSError* error)) handler;



@end
