#import <Foundation/Foundation.h>
#import "SWGMaintenance.h"
#import "SWGApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGUtilMaintenanceApi: NSObject <SWGApi>

extern NSString* kSWGUtilMaintenanceApiErrorDomain;
extern NSInteger kSWGUtilMaintenanceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Remove maintenance info
/// 
///
/// 
///  code:200 message:"OK",
///  code:204 message:"No Content",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden"
///
/// @return 
-(NSURLSessionTask*) deleteUsingDELETE1WithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// Get current maintenance info
/// Get current maintenance info. 404 if no maintenance.
///
/// 
///  code:200 message:"maintenance",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"no maintenance"
///
/// @return SWGMaintenance*
-(NSURLSessionTask*) getUsingGET1WithCompletionHandler: 
    (void (^)(SWGMaintenance* output, NSError* error)) handler;


/// Set current maintenance info
/// 
///
/// @param maintenance The Maintenance Object (optional)
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return 
-(NSURLSessionTask*) postUsingPOSTWithMaintenance: (SWGMaintenance*) maintenance
    completionHandler: (void (^)(NSError* error)) handler;


/// Set current maintenance info
/// 
///
/// @param maintenance The Maintenance Object (optional)
/// 
///  code:200 message:"OK",
///  code:201 message:"Created",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return 
-(NSURLSessionTask*) postUsingPUTWithMaintenance: (SWGMaintenance*) maintenance
    completionHandler: (void (^)(NSError* error)) handler;



@end
