#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGNestedCategory.h"
#import "SWGProperty.h"


@protocol SWGArticleResource
@end

@interface SWGArticleResource : SWGObject

/* Whether the article is active 
 */
@property(nonatomic) NSNumber* active;
/* A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type [optional]
 */
@property(nonatomic) NSDictionary<SWGProperty>* additionalProperties;
/* The body of the article 
 */
@property(nonatomic) NSString* body;
/* The category for the article 
 */
@property(nonatomic) SWGNestedCategory* category;
/* The date/time this resource was created in seconds since unix epoch [optional]
 */
@property(nonatomic) NSNumber* createdDate;
/* The id of the article [optional]
 */
@property(nonatomic) NSString* _id;
/* The tags for the article [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;
/* An article template this article is validated against (private). May be null and no validation of additional_properties will be done [optional]
 */
@property(nonatomic) NSString* template;
/* The title of the article 
 */
@property(nonatomic) NSString* title;
/* The date/time this resource was last updated in seconds since unix epoch [optional]
 */
@property(nonatomic) NSNumber* updatedDate;

@end
