#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGActionVariableResource
@end

@interface SWGActionVariableResource : SWGObject

/* The name of the variable 
 */
@property(nonatomic) NSString* name;
/* Whether this variable is optional and can be left out/null 
 */
@property(nonatomic) NSNumber* optional;
/* The type of the variable (see variable type endpoint for list) 
 */
@property(nonatomic) NSString* type;

@end
