#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGProperty.h"


@protocol SWGArtist
@end

@interface SWGArtist : SWGObject


@property(nonatomic) NSDictionary<SWGProperty>* additionalProperties;

@property(nonatomic) NSNumber* born;

@property(nonatomic) NSNumber* contributionCount;

@property(nonatomic) NSNumber* created;

@property(nonatomic) NSNumber* died;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* longDescription;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* priority;

@property(nonatomic) NSString* propertiesString;

@property(nonatomic) NSString* shortDescription;

@property(nonatomic) NSString* template;

@property(nonatomic) NSNumber* updated;

@end
