#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGBehavior.h"
#import "SWGPropertyDefinitionResource.h"


@protocol SWGBehaviorDefinitionResource
@end

@interface SWGBehaviorDefinitionResource : SWGObject

/* Description of the behavior [optional]
 */
@property(nonatomic) NSString* _description;
/* Pre-requisite behaviors that an item must have in order to also have this behavior [optional]
 */
@property(nonatomic) NSArray<SWGBehavior>* prerequisiteBehaviors;
/* Configurable properties of the behavior 
 */
@property(nonatomic) NSArray<SWGPropertyDefinitionResource>* properties;
/* The behavior type 
 */
@property(nonatomic) NSString* typeHint;

@end
