#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGBreTriggerParameterDefinition
@end

@interface SWGBreTriggerParameterDefinition : SWGObject

/* The name of the parameter. This is used as the unique identifier of this parameter 
 */
@property(nonatomic) NSString* name;
/* The variable type of this parameter. See Bre Variables endpoint for list 
 */
@property(nonatomic) NSString* type;

@end
