#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGActivityEntitlementResource.h"
#import "SWGRewardSetResource.h"
#import "SWGSelectedSettingResource.h"


@protocol SWGChallengeActivityResource
@end

@interface SWGChallengeActivityResource : SWGObject

/* The id of the activity 
 */
@property(nonatomic) NSNumber* activityId;
/* The id of the challenge [optional]
 */
@property(nonatomic) NSNumber* challengeId;
/* The entitlement item needed to participate in the activity as part of this event. Null indicates free entry. When creating/updating only id is used. Item must be pre-existing [optional]
 */
@property(nonatomic) SWGActivityEntitlementResource* entitlement;
/* The unique ID for this resource [optional]
 */
@property(nonatomic) NSNumber* _id;
/* The rewards to give at the end of each occurence of the activity. When creating/updating only id is used. Reward set must be pre-existing [optional]
 */
@property(nonatomic) SWGRewardSetResource* rewardSet;
/* The list of settings and the select options [optional]
 */
@property(nonatomic) NSArray<SWGSelectedSettingResource>* settings;

@end
