#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCreateBillingAgreementRequest
@end

@interface SWGCreateBillingAgreementRequest : SWGObject

/* The endpoint URL to which PayPal should forward the user if they cancel (do not accept) the agreement 
 */
@property(nonatomic) NSString* cancelUrl;
/* The endpoint URL to which PayPal should forward the user after they accept the agreement. This endpoint will receive information needed for the next step 
 */
@property(nonatomic) NSString* returnUrl;
/* The ID of the user. Defaults to the logged in user [optional]
 */
@property(nonatomic) NSNumber* userId;

@end
