#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCommentSearch
@end

@interface SWGCommentSearch : SWGObject


@property(nonatomic) NSString* content;

@property(nonatomic) NSString* context;

@property(nonatomic) NSNumber* contextId;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* ownerId;

@property(nonatomic) NSString* ownerUsername;

@end
