#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCommentSearch
@end

@interface SWGCommentSearch : SWGObject


@property(nonatomic) NSString* content;

@property(nonatomic) NSString* context;

@property(nonatomic) NSNumber* contextId;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* ownerId;

@property(nonatomic) NSString* ownerUsername;

@end
