#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCountry
@end

@interface SWGCountry : SWGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* iso2;

@property(nonatomic) NSString* iso3;

@property(nonatomic) NSString* name;

@end
