#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGDiscount.h"


@protocol SWGCartLineItem
@end

@interface SWGCartLineItem : SWGObject


@property(nonatomic) NSString* currencyCode;

@property(nonatomic) NSString* _description;

@property(nonatomic) SWGDiscount* discount;

@property(nonatomic) NSNumber* lineTotal;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* originalLineTotal;

@property(nonatomic) NSNumber* originalUnitPrice;

@property(nonatomic) NSNumber* qty;

@property(nonatomic) NSString* saleName;

@property(nonatomic) NSString* sku;

@property(nonatomic) NSString* skuDescription;

@property(nonatomic) NSNumber* storeItemId;

@property(nonatomic) NSArray<NSString*>* tags;

@property(nonatomic) NSString* thumbUrl;

@property(nonatomic) NSNumber* unitPrice;

@property(nonatomic) NSNumber* vendorId;

@property(nonatomic) NSString* vendorName;

@end
