#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCreatePayPalPaymentRequest
@end

@interface SWGCreatePayPalPaymentRequest : SWGObject

/* The endpoint URL to which PayPal should forward the user to if they cancel the checkout process 
 */
@property(nonatomic) NSString* cancelUrl;
/* The ID of an invoice to pay 
 */
@property(nonatomic) NSNumber* invoiceId;
/* The endpoint URL to which PayPal should forward the user after they accept. This endpoint will receive information needed for the next step 
 */
@property(nonatomic) NSString* returnUrl;

@end
