#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGBehavior.h"


@protocol SWGEntitlementItem
@end

@interface SWGEntitlementItem : SWGObject

/* The behaviors linked to the item, describing various options and interactions. May not be included in item lists [optional]
 */
@property(nonatomic) NSArray<SWGBehavior>* behaviors;
/* The date the item was created, unix timestamp in seconds [optional]
 */
@property(nonatomic) NSNumber* createdDate;
/* The id of the item [optional]
 */
@property(nonatomic) NSNumber* _id;
/* A long description of the item [optional]
 */
@property(nonatomic) NSString* longDescription;
/* The name of the item 
 */
@property(nonatomic) NSString* name;
/* A short description of the item, max 255 chars [optional]
 */
@property(nonatomic) NSString* shortDescription;
/* A number to use in sorting items.  Default 500 [optional]
 */
@property(nonatomic) NSNumber* sort;
/* The type of the item 
 */
@property(nonatomic) NSString* typeHint;
/* The unique key for the item [optional]
 */
@property(nonatomic) NSString* uniqueKey;
/* The date the item was last updated, unix timestamp in seconds [optional]
 */
@property(nonatomic) NSNumber* updatedDate;

@end
