#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGInvoiceLogEntry
@end

@interface SWGInvoiceLogEntry : SWGObject

/* The date this event occured as a unix timestamp in seconds [optional]
 */
@property(nonatomic) NSNumber* date;
/* The ID of the invoice [optional]
 */
@property(nonatomic) NSNumber* invoiceId;
/* A message describing the event [optional]
 */
@property(nonatomic) NSString* message;
/* The type of event [optional]
 */
@property(nonatomic) NSString* type;

@end
