#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGBehavior.h"


@protocol SWGItemBehaviorDefinitionResource
@end

@interface SWGItemBehaviorDefinitionResource : SWGObject

/* The default version of the behavior 
 */
@property(nonatomic) SWGBehavior* behavior;
/* Whether the behavior's values can be modified 
 */
@property(nonatomic) NSNumber* modifiable;
/* Whether the behavior can be removed 
 */
@property(nonatomic) NSNumber* required;

@end
