#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGInvoiceItemResource
@end

@interface SWGInvoiceItemResource : SWGObject


@property(nonatomic) NSNumber* affiliateId;

@property(nonatomic) NSString* bundleSku;

@property(nonatomic) NSString* currentFulfillmentStatus;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* invoiceId;

@property(nonatomic) NSNumber* itemId;

@property(nonatomic) NSString* itemName;

@property(nonatomic) NSNumber* originalTotalPrice;

@property(nonatomic) NSNumber* originalUnitPrice;

@property(nonatomic) NSNumber* qty;

@property(nonatomic) NSString* saleName;

@property(nonatomic) NSString* sku;

@property(nonatomic) NSString* skuDescription;

@property(nonatomic) NSNumber* systemPrice;

@property(nonatomic) NSNumber* totalPrice;

@property(nonatomic) NSString* typeHint;

@property(nonatomic) NSNumber* unitPrice;

@end
