#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGLeaderboardEntryResource.h"


@protocol SWGLeaderboardResource
@end

@interface SWGLeaderboardResource : SWGObject

/* The paginated list of user results, in order from best to worst [optional]
 */
@property(nonatomic) NSArray<SWGLeaderboardEntryResource>* entries;
/* The id of the leaderboard [optional]
 */
@property(nonatomic) NSNumber* _id;
/* The name of the strategy that defines how entries are stored and compared [optional]
 */
@property(nonatomic) NSString* strategy;

@end
