#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGMaintenance
@end

@interface SWGMaintenance : SWGObject

/* Whether access to the system has been locked 
 */
@property(nonatomic) NSNumber* accessLocked;
/* A simple object of any schema for client side use and processing [optional]
 */
@property(nonatomic) NSObject* details;
/* User displayable message about the maintenance 
 */
@property(nonatomic) NSString* message;

@end
