#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGNestedCategory
@end

@interface SWGNestedCategory : SWGObject

/* Whether the category is active [optional]
 */
@property(nonatomic) NSNumber* active;
/* The id of the category 
 */
@property(nonatomic) NSString* _id;
/* The name of the category [optional]
 */
@property(nonatomic) NSString* name;

@end
