#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGPollAnswerResource
@end

@interface SWGPollAnswerResource : SWGObject

/* The number of uesrs that selected this answer [optional]
 */
@property(nonatomic) NSNumber* count;
/* The key to the answer (for code reference) 
 */
@property(nonatomic) NSString* key;
/* The text of the answer (for user display) 
 */
@property(nonatomic) NSString* text;

@end
