#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGRole.h"


@protocol SWGPermission
@end

@interface SWGPermission : SWGObject


@property(nonatomic) NSNumber* createdDate;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* locked;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* parent;

@property(nonatomic) NSString* permission;

@property(nonatomic) NSArray<SWGRole>* permissionRole;

@property(nonatomic) NSNumber* updatedDate;

@end
