#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGSimpleUserResource.h"


@protocol SWGPollResponseResource
@end

@interface SWGPollResponseResource : SWGObject

/* The answer to the poll 
 */
@property(nonatomic) NSString* answer;
/* The date the poll was answered, in seconds since unix epoc [optional]
 */
@property(nonatomic) NSNumber* answeredDate;
/* The id of the poll response [optional]
 */
@property(nonatomic) NSString* _id;
/* The id of the poll 
 */
@property(nonatomic) NSString* pollId;
/* The user 
 */
@property(nonatomic) SWGSimpleUserResource* user;

@end
