#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGPermissionResource.h"


@protocol SWGRoleResource
@end

@interface SWGRoleResource : SWGObject

/* The number of clients this role is assigned to [optional]
 */
@property(nonatomic) NSNumber* clientCount;
/* The date the role was added. Unix timestamp in seconds [optional]
 */
@property(nonatomic) NSNumber* createdDate;
/* Whether a role is locked from being deleted [optional]
 */
@property(nonatomic) NSNumber* locked;
/* The name of the role used for display purposes [optional]
 */
@property(nonatomic) NSString* name;
/* The keyword that defines the role [optional]
 */
@property(nonatomic) NSString* role;
/* The list of permissions this role has [optional]
 */
@property(nonatomic) NSArray<SWGPermissionResource>* rolePermission;
/* The number of users this role is assigned to [optional]
 */
@property(nonatomic) NSNumber* userCount;

@end
