#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGPermission.h"


@protocol SWGRole
@end

@interface SWGRole : SWGObject


@property(nonatomic) NSNumber* clientCount;

@property(nonatomic) NSNumber* createdDate;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* locked;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* role;

@property(nonatomic) NSArray<SWGPermission>* rolePermission;

@property(nonatomic) NSNumber* userCount;

@end
