#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGUserAchievementResource.h"


@protocol SWGUserAchievementGroupResource
@end

@interface SWGUserAchievementGroupResource : SWGObject

/* The list of achievements associated with the group 
 */
@property(nonatomic) NSArray<SWGUserAchievementResource>* achievements;
/* The name of the group.  If used by Leveling, this will represent the level name 
 */
@property(nonatomic) NSString* groupName;
/* The id of the achievement progress [optional]
 */
@property(nonatomic) NSString* _id;
/* The current progress of the user on the group 
 */
@property(nonatomic) NSNumber* progress;
/* The id of the user whose progress is being tracked 
 */
@property(nonatomic) NSNumber* userId;

@end
