#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGUserBaseResource
@end

@interface SWGUserBaseResource : SWGObject

/* The url of the user's avatar image [optional]
 */
@property(nonatomic) NSString* avatarUrl;
/* The chosen display name of the user, defaults to username if not present [optional]
 */
@property(nonatomic) NSString* displayName;
/* The user's email address (private). May be required and/or unique depending on system configuration (both on by default). Must match standard email requirements if provided (RFC 2822) 
 */
@property(nonatomic) NSString* email;
/* The user's full name (private) [optional]
 */
@property(nonatomic) NSString* fullname;
/* The id of the user [optional]
 */
@property(nonatomic) NSNumber* _id;
/* The login username for the user (private). May be set to match email if system does not require usernames separately. 
 */
@property(nonatomic) NSString* username;

@end
