#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Knetik Platform API Documentation Latest
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: Latest
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGWalletTotalResponse
@end

@interface SWGWalletTotalResponse : SWGObject

/* The currency code [optional]
 */
@property(nonatomic) NSString* currencyCode;
/* The sum of all wallets in the system for this currency [optional]
 */
@property(nonatomic) NSNumber* total;

@end
